"""fix

Revision ID: 2752a760d97b
Revises: 73e2c48d9ab9
Create Date: 2025-09-30 17:39:46.636101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '2752a760d97b'
down_revision: Union[str, Sequence[str], None] = '73e2c48d9ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_books_uid', 'books', ['uid'])
    op.create_unique_constraint('uq_user_accounts_uid', 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_accounts_uid', 'user_accounts', type_='unique')
    op.drop_constraint('uq_books_uid', 'books', type_='unique')
    # ### end Alembic commands ###
