"""fix

Revision ID: 73e2c48d9ab9
Revises: ec31b97a5fc7
Create Date: 2025-09-29 23:37:46.410321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '73e2c48d9ab9'
down_revision: Union[str, Sequence[str], None] = 'ec31b97a5fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'uid',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'uid',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
